Repository ever-co/ever-teams, pull requests merged in 2024-04, with the labels that each got.

#2349 2338 bug synchronize task progression in kanban view
  apps/web/app/[locale]/kanban/page.tsx
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/features/team-members-kanban-view.tsx
Labels: UI/UX, Improvement

#2351 2350 fix linting and warnings
  .husky/pre-commit
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/components/inputs/auth-code-input.tsx
Labels: Investigation

#2357 [Feature]: Edit Status for Kanban
  apps/web/app/[locale]/kanban/page.tsx
  apps/web/app/hooks/features/useKanban.ts
  apps/web/components/pages/kanban/edit-status-modal.tsx
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/features/team-members-kanban-view.tsx
Labels: feature

#2361 [Fix]: task status ids are fixed in kanban board
  apps/web/app/hooks/features/useTaskInput.ts
  apps/web/app/hooks/features/useTeamTasks.ts
Labels: bug

#2364 [Fix]: Head Document title
  apps/web/app/[locale]/kanban/page.tsx
  apps/web/app/[locale]/layout.tsx
  apps/web/app/[locale]/profile/[memberId]/page.tsx
  apps/web/lib/components/image-overlapper.tsx
  apps/web/lib/features/task/task-item.tsx
  apps/web/lib/features/team/user-team-block/user-info.tsx
  apps/web/lib/features/team/user-team-card/user-info.tsx
  apps/web/lib/features/user-nav-menu.tsx
Labels: bug, enhancement

#2379 [Bug]: Re-rendering issue in user profile page
  apps/web/app/hooks/useInfinityFetch.ts
  apps/web/next.config.js
Labels: bug

#2376 [Setting]: fixed the settings page issues
  apps/web/app/[locale]/settings/layout.tsx
  apps/web/app/hooks/useLeftSettingData.ts
  apps/web/components/ui/scroll-bar.tsx
  apps/web/lib/components/color-picker.tsx
  apps/web/lib/components/dropdown.tsx
  apps/web/lib/components/pagination.tsx
  apps/web/lib/settings/list-card.tsx
  apps/web/lib/settings/member-setting.tsx
  apps/web/lib/settings/personal-setting-form.tsx
  apps/web/lib/settings/timezone-dropdown.tsx
Labels: bug

#2377 2371 bug home page fixes
  .cspell.json
  apps/web/app/[locale]/kanban/page.tsx
  apps/web/app/[locale]/page-component.tsx
  apps/web/components/ui/data-table.tsx
  apps/web/lib/features/team-members-kanban-view.tsx
  apps/web/lib/features/team-members-table-view.tsx
  apps/web/lib/features/team-members.tsx
  apps/web/lib/features/team/user-team-block/user-team-block-header.tsx
  apps/web/lib/features/team/user-team-card/task-info.tsx
  apps/web/lib/features/team/user-team-card/task-skeleton.tsx
  apps/web/lib/features/team/user-team-table/user-team-table-header.tsx
  apps/web/lib/layout/main-layout.tsx
  apps/web/messages/ar.json
  apps/web/messages/bg.json
  apps/web/messages/de.json
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/fr.json
  apps/web/messages/he.json
  apps/web/messages/it.json
  apps/web/messages/nl.json
  apps/web/messages/pl.json
  apps/web/messages/pt.json
  apps/web/messages/ru.json
  apps/web/messages/zh.json
Labels: bug

#2387 Improvements
  apps/web/app/[locale]/settings/layout.tsx
  apps/web/lib/features/team/user-team-table/user-team-table-header.tsx
Labels: WEB, Improvement

#2414 fix(Task-Issue): fix the issue of task not saving
  apps/web/app/hooks/features/useTaskInput.ts
  apps/web/lib/features/task/task-input-kanban.tsx
  apps/web/lib/features/task/task-input.tsx
Labels: bug

#2428 fix(Color): z-index added for color dropdown
  apps/web/lib/components/Kanban.tsx
Labels: bug, Improvement

#2440 2439 update search components not found
  .vscode/settings.json
Labels: bug

#2441 [2401]: dropdown height make contain
  apps/web/lib/components/dropdown.tsx
Labels: bug

#2459 2401 bug team selector collapse does not work
  apps/web/lib/components/dropdown.tsx
Labels: bug
