Repository ever-co/ever-teams, pull requests merged in 2024-03, with the labels that each got.

#2254 Fix: Errors
  .cspell.json
  apps/web/app/[locale]/page-component.tsx
  apps/web/app/[locale]/profile/[memberId]/page.tsx
  apps/web/app/[locale]/settings/layout.tsx
  apps/web/app/[locale]/settings/personal/page.tsx
  apps/web/app/[locale]/settings/team/page.tsx
  apps/web/lib/features/task/task-input.tsx
  apps/web/lib/features/user-profile-tasks.tsx
  apps/web/lib/settings/invitation-table.tsx
Labels: WEB

#2260 Fix: Invite DropDown
  apps/web/lib/components/auto-complete-dropdown.tsx
  apps/web/lib/features/team/invite/invite-email-dropdown.tsx
Labels: WEB, Improvement

#2263 [fix]: move the 404 page into main pages
  apps/web/app/[locale]/404.tsx
Labels: bug, enhancement

#2267 Fix: minors
  apps/web/app/[locale]/page-component.tsx
  apps/web/app/[locale]/settings/personal/page.tsx
  apps/web/app/[locale]/settings/team/page.tsx
  apps/web/lib/features/task/task-card.tsx
  apps/web/lib/features/team-member-cell.tsx
  apps/web/lib/features/team-members.tsx
  apps/web/lib/features/team/invite/user-invite-card.tsx
  apps/web/lib/features/team/user-team-block/index.tsx
  apps/web/lib/features/team/user-team-block/user-team-block-header.tsx
  apps/web/lib/features/team/user-team-card/index.tsx
  apps/web/lib/features/team/user-team-card/task-info.tsx
  apps/web/lib/features/team/user-team-table/user-team-table-header.tsx
  apps/web/lib/features/timer/timer.tsx
Labels: Improvement

#2275 Feat: Full Width Switch Mode
  apps/web/app/[locale]/page-component.tsx
  apps/web/app/[locale]/settings/layout.tsx
  apps/web/lib/components/container.tsx
  apps/web/lib/components/toggler.tsx
  apps/web/lib/features/task/task-card.tsx
  apps/web/lib/features/team/user-team-card/index.tsx
  apps/web/lib/features/team/user-team-card/task-skeleton.tsx
  apps/web/lib/features/user-nav-menu.tsx
  apps/web/lib/features/user-profile-tasks.tsx
  apps/web/lib/layout/main-layout.tsx
  apps/web/lib/settings/left-side-setting-menu.tsx
  apps/web/next.config.js
  apps/web/styles/globals.css
Labels: enhancement, WEB

#2284 Feat: add missing Translations
  apps/web/lib/features/user-nav-menu.tsx
  apps/web/messages/ar.json
  apps/web/messages/bg.json
  apps/web/messages/de.json
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/fr.json
  apps/web/messages/he.json
  apps/web/messages/it.json
  apps/web/messages/nl.json
  apps/web/messages/pl.json
  apps/web/messages/pt.json
  apps/web/messages/ru.json
  apps/web/messages/zh.json
  apps/web/public/locales/ar/common.json
  apps/web/public/locales/bg/common.json
  apps/web/public/locales/de/common.json
  apps/web/public/locales/en/common.json
  apps/web/public/locales/es/common.json
  apps/web/public/locales/fr/common.json
  apps/web/public/locales/he/common.json
  apps/web/public/locales/it/common.json
  apps/web/public/locales/nl/common.json
  apps/web/public/locales/pl/common.json
  apps/web/public/locales/pt/common.json
  apps/web/public/locales/ru/common.json
  apps/web/public/locales/zh/common.json
Labels: WEB, Improvement

#2290 2277 feature modifications in kanban 2
  apps/web/app/[locale]/kanban/page.tsx
  apps/web/app/hooks/features/useKanban.ts
  apps/web/app/hooks/features/useTeamTasks.ts
  apps/web/components/pages/kanban/create-task-modal.tsx
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/components/image-overlapper.tsx
  apps/web/lib/components/kanban-card.tsx
  apps/web/lib/features/task/task-input-kanban.tsx
Labels: enhancement, good first issue, Improvement

#2298 2291 feature modifications in kanban no 3
  apps/web/app/[locale]/kanban/page.tsx
  apps/web/app/hooks/features/useKanban.ts
  apps/web/components/pages/kanban/search-bar.tsx
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/components/kanban-card.tsx
  apps/web/lib/features/task/task-filters.tsx
  apps/web/lib/features/team-members-kanban-view.tsx
  apps/web/lib/features/team/user-team-card/index.tsx
  apps/web/lib/layout/main-layout.tsx
Labels: Improvement

#2302 [Fix]: fix the header tabs of home-pages
  apps/web/app/[locale]/page-component.tsx
  apps/web/components/pages/main/header-tabs.tsx
  apps/web/components/ui/data-table.tsx
  apps/web/lib/components/kanban-card.tsx
  apps/web/lib/features/task/task-all-status-type.tsx
  apps/web/lib/features/team-member-cell.tsx
  apps/web/lib/features/team-members-block-view.tsx
  apps/web/lib/features/team-members-card-view.tsx
  apps/web/lib/features/team-members-table-view.tsx
  apps/web/lib/features/team/user-team-card/task-info.tsx
  apps/web/lib/features/team/user-team-card/user-team-card-menu.tsx
Labels: enhancement

#2306 [Fix]: epic and labels filter added
  apps/web/app/[locale]/kanban/page.tsx
  apps/web/app/hooks/features/useKanban.ts
  apps/web/lib/features/task/task-status.tsx
Labels: enhancement

#2313 [Bug]: maintainence navigation
  apps/web/app/[locale]/layout.tsx
Labels: bug

#2311 [Feature]: labels slider + drag header + create task label.
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/components/image-overlapper.tsx
  apps/web/lib/components/kanban-card.tsx
  apps/web/lib/features/task/task-all-status-type.tsx
  apps/web/lib/features/task/task-input-kanban.tsx
Labels: enhancement

#2315 Improvements of UI
  apps/web/app/[locale]/kanban/page.tsx
  apps/web/app/[locale]/settings/layout.tsx
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/settings/member-table.tsx
Labels: WEB, Improvement

#2319 Fix: Task Input section & Headers Team Members Views
  apps/web/app/[locale]/page-component.tsx
  apps/web/components/ui/data-table.tsx
  apps/web/lib/features/team-member-header.tsx
  apps/web/lib/features/team-members-block-view.tsx
  apps/web/lib/features/team-members-card-view.tsx
  apps/web/lib/features/team-members-table-view.tsx
  apps/web/lib/features/team-members.tsx
  apps/web/lib/features/team/user-team-block/user-team-block-header.tsx
  apps/web/lib/features/team/user-team-card/task-skeleton.tsx
  apps/web/lib/features/team/user-team-table/user-team-table-header.tsx
  apps/web/lib/layout/main-header.tsx
Labels: WEB, Improvement

#2323 fix: align task Summary on Team Member List View ( Card & Table)
  apps/web/lib/features/task/task-all-status-type.tsx
  apps/web/lib/features/team-member-cell.tsx
  apps/web/lib/features/team/user-team-card/task-info.tsx
Labels: WEB, Improvement

#2325 2314 feature modification in kanban 6
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/features/team-members-kanban-view.tsx
Labels: enhancement

#2331 Fix: Allow Managers to see Activity of User
  apps/web/app/[locale]/profile/[memberId]/page.tsx
  apps/web/lib/features/team/user-team-card/index.tsx
Labels: Improvement

#2333 2326 feature adding ids of tasks details
  apps/web/app/hooks/features/useKanban.ts
  apps/web/app/hooks/features/useTeamTasks.ts
  apps/web/app/interfaces/ITask.ts
  apps/web/app/services/client/api/tasks.ts
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/features/team-members-kanban-view.tsx
Labels: bug, enhancement, Improvement

#2336 2328 improvement task type icon of task cards on kanban view
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/features/team-members-kanban-view.tsx
Labels: enhancement

#2339 2335 feature add a dropdown to filter kanban by task types
  apps/web/app/[locale]/kanban/page.tsx
  apps/web/app/hooks/features/useKanban.ts
  apps/web/app/hooks/features/useTaskInput.ts
  apps/web/lib/components/kanban-card.tsx
  apps/web/lib/features/task/task-issue.tsx
  apps/web/lib/features/team-members-kanban-view.tsx
Labels: enhancement

#2340 2337 bug drag and drop a task from a column to an empty column in kanban view
  apps/web/lib/components/Kanban.tsx
  apps/web/lib/features/team-members-kanban-view.tsx
Labels: bug

#2342 [Design]: design setting and re-fetch
  apps/web/app/[locale]/settings/layout.tsx
  apps/web/app/[locale]/settings/team/page.tsx
  apps/web/lib/components/pagination.tsx
Labels: bug, WEB
