Repository ever-co/ever-teams, pull requests merged in 2024-05, with the labels that each got.

#2480 feat: worked on task edit
  apps/web/app/hooks/features/useTeamMemberCard.ts
  apps/web/app/stores/team-tasks.ts
  apps/web/components/pages/kanban/menu-kanban-card.tsx
  apps/web/lib/components/kanban-card.tsx
  apps/web/lib/features/task/task-input-kanban.tsx
Labels: bug

#2493 Task details page "Planned" Block
  apps/web/app/api/daily-plan/task/[taskId]/route.ts
  apps/web/app/hooks/features/useDailyPlan.ts
  apps/web/app/services/client/api/daily-plan.ts
  apps/web/app/services/server/requests/daily-plan.ts
  apps/web/app/stores/daily-plan.ts
  apps/web/components/pages/task/details-section/blocks/task-plans.tsx
  apps/web/components/pages/task/task-details-aside.tsx
Labels: WEB, Ever Teams

#2495 [Improve] Add translations to the team block headers
  apps/web/components/pages/main/header-tabs.tsx
  apps/web/lib/features/team/user-team-block/user-team-block-header.tsx
  apps/web/messages/ar.json
  apps/web/messages/bg.json
  apps/web/messages/de.json
  apps/web/messages/en.json
  apps/web/messages/es.json
  apps/web/messages/fr.json
  apps/web/messages/he.json
  apps/web/messages/it.json
  apps/web/messages/nl.json
  apps/web/messages/pl.json
  apps/web/messages/pt.json
  apps/web/messages/ru.json
  apps/web/messages/zh.json
  apps/web/public/locales/ar/common.json
  apps/web/public/locales/bg/common.json
  apps/web/public/locales/de/common.json
  apps/web/public/locales/en/common.json
  apps/web/public/locales/es/common.json
  apps/web/public/locales/fr/common.json
  apps/web/public/locales/he/common.json
  apps/web/public/locales/it/common.json
  apps/web/public/locales/nl/common.json
  apps/web/public/locales/pl/common.json
  apps/web/public/locales/pt/common.json
  apps/web/public/locales/ru/common.json
  apps/web/public/locales/zh/common.json
Labels: Don't Merge

#2499 feat: fix the create status issue
  apps/web/app/interfaces/ITaskStatus.ts
  apps/web/lib/settings/task-statuses-form.tsx
Labels: bug

#2503 bug: header loading and estimate fixes
  apps/web/app/hooks/features/useTaskEstimation.ts
  apps/web/lib/features/team/user-team-card/index.tsx
  apps/web/lib/features/team/user-team-card/task-estimate.tsx
Labels: bug

#2504 Daily Plan, Plan from Kanban, 'Unplan' task,
  .cspell.json
  apps/web/app/[locale]/profile/[memberId]/page.tsx
  apps/web/app/api/daily-plan/plan/[planId]/route.ts
  apps/web/app/hooks/features/useAuthTeamTasks.ts
  apps/web/app/hooks/features/useDailyPlan.ts
  apps/web/app/services/client/api/daily-plan.ts
  apps/web/app/services/server/requests/daily-plan.ts
  apps/web/app/stores/daily-plan.ts
  apps/web/components/pages/kanban/menu-kanban-card.tsx
  apps/web/components/pages/task/details-section/blocks/task-plans.tsx
  apps/web/lib/features/daily-plan/add-task-to-plan.tsx
  apps/web/lib/features/daily-plan/create-daily-plan-form-modal.tsx
  apps/web/lib/features/task/daily-plan/outstanding.tsx
  apps/web/lib/features/task/task-card.tsx
  apps/web/lib/features/task/task-filters.tsx
  apps/web/lib/features/user-profile-plans.tsx
Labels: WEB, Ever Teams

#2507 2498 use single lib for translation
  .cspell.json
  apps/web/app/hooks/useLanguage.ts
  apps/web/ni18n.config.ts
  apps/web/package.json
  apps/web/public/locales/ar/common.json
  apps/web/public/locales/bg/common.json
  apps/web/public/locales/de/common.json
  apps/web/public/locales/en/common.json
  apps/web/public/locales/es/common.json
  apps/web/public/locales/fr/common.json
  apps/web/public/locales/he/common.json
  apps/web/public/locales/it/common.json
  apps/web/public/locales/nl/common.json
  apps/web/public/locales/pl/common.json
  apps/web/public/locales/pt/common.json
  apps/web/public/locales/ru/common.json
  apps/web/public/locales/zh/common.json
Labels: duplicate

#2511 Daily plan actions
  apps/web/app/api/daily-plan/remove-task/[planId]/route.ts
  apps/web/app/hooks/features/useDailyPlan.ts
  apps/web/app/services/client/api/daily-plan.ts
  apps/web/app/services/server/requests/daily-plan.ts
  apps/web/lib/features/task/daily-plan/future-tasks.tsx
  apps/web/lib/features/task/task-card.tsx
  apps/web/lib/features/user-profile-plans.tsx
Labels: WEB, Ever Teams

#2515 Refact daily plan requests and types
  .cspell.json
  apps/web/app/api/daily-plan/[id]/route.ts
  apps/web/app/api/daily-plan/plan/[planId]/route.ts
  apps/web/app/api/daily-plan/remove-task/[planId]/route.ts
  apps/web/app/hooks/features/useDailyPlan.ts
  apps/web/app/interfaces/IBaseModel.ts
  apps/web/app/interfaces/IDailyPlan.ts
  apps/web/app/interfaces/IEmployee.ts
  apps/web/app/services/client/api/daily-plan.ts
  apps/web/app/services/server/requests/daily-plan.ts
  apps/web/lib/features/daily-plan/create-daily-plan-form-modal.tsx
  apps/web/lib/features/task/daily-plan/future-tasks.tsx
  apps/web/lib/features/task/task-card.tsx
  apps/web/lib/features/user-profile-plans.tsx
Labels: WEB, Ever Teams

#2521 Fix: Unassigned Team Members
  apps/web/lib/features/task/task-assign-button.tsx
  apps/web/lib/features/task/task-card.tsx
Labels: WEB, Ever Teams

#2523 Update React Query to latest
  apps/mobile/app/navigators/AppNavigator.tsx
  apps/mobile/app/screens/Authenticated/ProfileScreen/components/AssignTaskSection.tsx
  apps/mobile/app/screens/Authenticated/SettingScreen/components/LanguageForm.tsx
  apps/mobile/app/services/client/queries/invitation/invitations.ts
  apps/mobile/app/services/client/queries/language/index.ts
  apps/mobile/app/services/client/queries/organizationTeam/organization.ts
  apps/mobile/app/services/client/queries/task/stats.ts
  apps/mobile/app/services/client/queries/task/task-issue.ts
  apps/mobile/app/services/client/queries/task/task-labels.ts
  apps/mobile/app/services/client/queries/task/task-priority.ts
  apps/mobile/app/services/client/queries/task/task-sizes.ts
  apps/mobile/app/services/client/queries/task/task-status.ts
  apps/mobile/app/services/client/queries/task/task-version.ts
  apps/mobile/app/services/client/queries/task/tasks.ts
  apps/mobile/app/services/client/queries/timer/timer.ts
  apps/mobile/app/services/client/queries/user/user.ts
  apps/mobile/app/services/hooks/features/useSettings.ts
  apps/mobile/app/services/hooks/features/useTaskIssue.ts
  apps/mobile/app/services/hooks/features/useTaskLabels.ts
  apps/mobile/app/services/hooks/features/useTaskPriority.ts
  apps/mobile/app/services/hooks/features/useTaskSizes.ts
  apps/mobile/app/services/hooks/features/useTaskStatus.ts
  apps/mobile/app/services/hooks/features/useTaskVersion.ts
  apps/mobile/package.json
  apps/mobile/yarn.lock
Labels: dependencies

#2530 fix: breadcrumbs issue in setting page
  apps/web/app/[locale]/settings/layout.tsx
Labels: bug

#2518 Member profile page hide some tab options
  apps/mobile/app/services/interfaces/IOrganizationTeam.ts
  apps/web/app/hooks/features/useAuthenticateUser.ts
  apps/web/app/interfaces/IOrganizationTeam.ts
  apps/web/lib/components/switch.tsx
  apps/web/lib/features/task/daily-plan/future-tasks.tsx
  apps/web/lib/features/task/task-card.tsx
  apps/web/lib/features/task/task-filters.tsx
  apps/web/lib/features/user-profile-plans.tsx
  apps/web/lib/settings/integration-setting.tsx
  apps/web/lib/settings/team-setting-form.tsx
Labels: WEB, Gauzy, Ever Teams

#2542 Dynamic social logins for support only configured providers
  .cspell.json
  apps/web/.env.sample
  apps/web/app/[locale]/auth/social-logins-buttons.tsx
  apps/web/app/utils/check-provider-env-vars.ts
  apps/web/auth.ts
Labels: WEB, Ever Teams

#2545 Ability to Track time on "Task" page
  apps/web/app/hooks/features/useTimer.ts
  yarn.lock
Labels: enhancement

#2550 Fix task-card and plans null checks
  apps/web/lib/features/task/daily-plan/outstanding.tsx
  apps/web/lib/features/task/daily-plan/past-tasks.tsx
  apps/web/lib/features/task/task-card.tsx
  apps/web/lib/features/user-profile-plans.tsx
Labels: bug
