Repository ever-co/ever-teams, pull requests merged in 2025-09, with the labels that each got.

#4000 [Feature] Implement “Get My Permissions” api service
  apps/web/core/components/layouts/app/init-state.tsx
  apps/web/core/hooks/roles/use-role-permissions.ts
  apps/web/core/query/keys/index.ts
  apps/web/core/services/client/api/roles/role-permission.service.ts
  apps/web/core/stores/auth/role-permissions.ts
Labels: feature, UI/UX, Ever Teams

#4004 Fix: Etp 95 web bug task assignment fails with zod validation error missing user
  .cspell.json
  apps/web/core/components/optimized-components/tasks.tsx
  apps/web/core/components/pages/task/details-section/blocks/member-list-item.tsx
  apps/web/core/components/pages/task/details-section/blocks/member-section.tsx
  apps/web/core/components/pages/task/details-section/blocks/task-main-info.tsx
  apps/web/core/components/pages/task/details-section/components/task-label.tsx
  apps/web/core/hooks/organizations/teams/use-team-tasks.ts
  apps/web/core/hooks/tasks/use-task-member-management.ts
Labels: Improvement, Bug fix

#3981 Update select-workspace Sidebar UI screen
  apps/web/core/components/common/workspace-switcher.tsx
  apps/web/core/hooks/auth/use-authentication-passcode.ts
  apps/web/core/hooks/auth/use-authentication-password.ts
  apps/web/core/hooks/auth/use-current-org.ts
  apps/web/core/hooks/auth/use-workspace-switcher.ts
  apps/web/core/hooks/auth/use-workspaces.ts
  apps/web/core/lib/utils/date-comparison.utils.ts
  apps/web/core/services/client/api/auth/auth.service.ts
  apps/web/core/services/client/api/auth/workspace.service.ts
  apps/web/core/services/client/axios.ts
  apps/web/core/services/server/requests/auth.ts
  apps/web/core/stores/auth/workspaces.ts
  apps/web/core/types/schemas/team/organization-team.schema.ts
Labels: WEB, Improvement, Ever Teams

#4009 [FixBug] Prevent unexpected 403s for API calls with sensitive relations
  apps/web/app/[locale]/(main)/reports/weekly-limit/page.tsx
  apps/web/core/hooks/roles/use-role-permissions.ts
  apps/web/core/services/client/api/roles/role-permission.service.ts
  apps/web/core/services/client/api/timesheets/time-log.service.ts
  apps/web/core/services/server/requests/organization.ts
  apps/web/core/stores/auth/role-permissions.ts
  apps/web/core/types/schemas/role/role-permission-schema.ts
Labels: UI/UX, Improvement, Ever Teams

#4012 [FixBug] Unable to switch back to a specific team after selecting “All Teams” view
  apps/web/core/components/pages/teams/all-teams/all-teams-members-views/users-teams-block/user-team-active-task-times.tsx
  apps/web/core/components/pages/teams/all-teams/all-teams-members-views/users-teams-block/user-team-task-estimate.tsx
  apps/web/core/components/pages/teams/all-teams/all-teams-members-views/users-teams-card/user-card.tsx
  apps/web/core/components/pages/teams/all-teams/all-teams-members-views/users-teams-card/user-team-active-task-times.tsx
  apps/web/core/components/pages/teams/all-teams/all-teams-members-views/users-teams-card/user-team-task-estimate.tsx
  apps/web/core/components/teams/team-item.tsx
  apps/web/core/components/teams/teams-dropdown.tsx
Labels: UI/UX, WEB, Ever Teams, Bug fix

#4016 [FixBug] Infinite API calls to currency endpoint in Project Creation form (Financial Settings step)
  apps/web/core/components/features/projects/add-or-edit-project/steps/financial-settings-form.tsx
  apps/web/core/components/layouts/app/init-state.tsx
  apps/web/core/hooks/common/use-currencies.ts
  apps/web/core/types/interfaces/common/currency.ts
Labels: Ever Teams, Bug fix, performance

#4017 [FixBug] Broken UX/UI in Project Filters popup (dropdown & multi-select issues)
  apps/web/core/components/projects/filters-card-modal.tsx
Labels: UI/UX, Ever Teams, Bug fix

#4024 [Mobile]-Fix sentry config
  apps/mobile/.env.template
  apps/mobile/.gitignore
  apps/mobile/App.js
  apps/mobile/app.json
  apps/mobile/app.template.json
  apps/mobile/app/app.tsx
  apps/mobile/app/utils/crash-reporting.ts
  apps/mobile/metro.config.js
  apps/mobile/package.json
  apps/mobile/yarn.lock
Labels: Bug fix

#4022 [Task] Implement task estimation API service for per-member estimation
  apps/web/core/hooks/tasks/use-task-estimations.ts
  apps/web/core/services/client/api/tasks/task-estimations.service.ts
  apps/web/core/types/schemas/task/task.schema.ts
Labels: feature, Ever Teams
